// <auto-generated />

#nullable disable

using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Cleanuparr.Persistence.Migrations.Events
{
    [DbContext(typeof(EventsContext))]
    [Migration("20250614211246_InitialEvents")]
    partial class InitialEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Data.Models.Events.AppEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("TrackingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tracking_id");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_events_event_type");

                    b.HasIndex("Message")
                        .HasDatabaseName("ix_events_message");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_events_severity");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_events_timestamp");

                    b.ToTable("events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
