name: Pipeline

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  # pull_request:
  #   paths:
  #     - 'code/**'

jobs:
  build:
    uses: flmorg/testing/.github/workflows/build.yml@main
    secrets: inherit