on:
  push:
    branches:
      - main
    paths:
      - 'code/**'
  pull_request:
    paths:
      - 'code/**'

jobs:
  build:
    uses: flmorg/testing/.github/workflows/build.yml@main
    secrets: inherit